SET SERVEROUTPUT ON;
PROMPT ================================
PROMPT EJECUTANDO SCRIPT: TABLESPACES
PROMPT ================================

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE tbs_proyecto_datos
DATAFILE '/opt/oracle/oradata/XE/tbs_proyecto_datos01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE tbs_proyecto_indices
DATAFILE '/opt/oracle/oradata/XE/tbs_proyecto_indices01.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE tbs_proyecto_temp
TEMPFILE '/opt/oracle/oradata/XE/tbs_proyecto_temp01.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

COMMIT;