SET SERVEROUTPUT ON;
PROMPT ================================
PROMPT CREACION DE USUARIO DEL PROYECTO
PROMPT ================================

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER usuario_proyecto
IDENTIFIED BY Proyecto123
DEFAULT TABLESPACE tbs_proyecto_datos
TEMPORARY TABLESPACE tbs_proyecto_temp
QUOTA UNLIMITED ON tbs_proyecto_datos
QUOTA UNLIMITED ON tbs_proyecto_indices;

GRANT CREATE SESSION TO usuario_proyecto;

GRANT
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE SYNONYM,
    CREATE TYPE
TO usuario_proyecto;