SET SERVEROUTPUT ON;
PROMPT ================================
PROMPT EJECUTANDO SCRIPT: PROCEDIMIENTOS Y REPORTES
PROMPT ================================

CONNECT usuario_proyecto/Proyecto123@XEPDB1

CREATE OR REPLACE PROCEDURE GENERAR_REPORTE_RESUMEN (p_fecha_inicio IN DATE, p_fecha_fin IN DATE) IS
BEGIN
    DELETE FROM REPORTES_RESUMEN
    WHERE FECHA_INICIO = p_fecha_inicio
    AND FECHA_FIN = p_fecha_fin;

    INSERT INTO REPORTES_RESUMEN (FECHA_INICIO, FECHA_FIN, CATEGORY_NAME, CHANNEL_NAME, AGENT_NAME, TOTAL_TICKETS, PROMEDIO_CSAT, PROMEDIO_PRECIO, PROMEDIO_RESPUESTA)
    SELECT
        p_fecha_inicio,
        p_fecha_fin,
        cat.CATEGORY AS CATEGORY_NAME,
        can.CHANNEL_NAME,
        ag.AGENT_NAME,
        COUNT(*) AS TOTAL_TICKETS,
        AVG(t.CSAT_SCORE) AS PROMEDIO_CSAT,
        AVG(t.ITEM_PRICE) AS PROMEDIO_PRECIO,
        AVG(t.RESPONSE_TIME_MINUTES) AS PROMEDIO_RESPUESTA
    FROM
        FACT_SUPPORT_TICKETS t
        LEFT JOIN CATEGORIAS cat ON t.ID_CATEGORIA = cat.ID_CATEGORIA
        LEFT JOIN CANALES can ON t.ID_CANAL = can.ID_CANAL
        LEFT JOIN AGENTES ag ON t.ID_AGENTE = ag.ID_AGENTE
    WHERE
        t.ORDER_DATE_TIME BETWEEN CAST(p_fecha_inicio AS TIMESTAMP)
                            AND CAST(p_fecha_fin AS TIMESTAMP) + INTERVAL '23:59:59' HOUR TO SECOND
    GROUP BY
        cat.CATEGORY,
        can.CHANNEL_NAME,
        ag.AGENT_NAME;

    COMMIT;
END;
/

CREATE OR REPLACE VIEW VW_TICKETS_PIVOT AS
SELECT *
FROM (
    SELECT
        c.CATEGORY,
        ca.CHANNEL_NAME
    FROM
        FACT_SUPPORT_TICKETS t
        JOIN CATEGORIAS c ON t.ID_CATEGORIA = c.ID_CATEGORIA
        JOIN CANALES ca ON t.ID_CANAL = ca.ID_CANAL
) PIVOT (
    COUNT(CHANNEL_NAME)
    FOR CHANNEL_NAME IN (
        'Canal1' AS Canal1,
        'Canal2' AS Canal2,
        'Canal3' AS Canal3,
        'Canal4' AS Canal4,
        'Canal5' AS Canal5
    )
)
ORDER BY CATEGORY;

/*LOGICA DEL NEGOCIO*/

-- paquetes
-- ...
-- ...
-- ...

COMMIT;